<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Cadastrar Sítio</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/sitio/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
				<div class="control-group">
							<label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fNmSitio"  value="<?=$this->sNome;?>" class="required">
							</div>
						</div>
		

						<div class="control-group">
							<label class="control-label">UF <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select tabindex="3" name="nIdMunicipio" class="required" style="width: 200px;">
									<?php
									foreach ($this->vMunicipio as $municipio) {
										if ($municipio["id"] == $this->fIdMunicipio)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$municipio["id"]?>" <?=$sSel?>><?=$municipio["nm_municipio"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
                                                        
                                                            <div class="control-group">
							<label class="control-label">Latitude <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" class="required" name="flatitude" value="<?=$this->flatitude;?>">
							</div>
						</div>
                                            
                                               <div class="control-group">
							<label class="control-label">Longitude <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" class="required" name="flongitude" value="<?=$this->flongitude;?>">
							</div>
						</div>
						</div>
                                            
                                            
                                            	<div class="control-group">
							<label class="control-label">Núcleo :</label>
							<div class="controls">
								<select tabindex="3" name="nIdNucleo"  style="width: 200px;">
									<?php
									foreach ($this->vNucleo as $nucleo) {
										if ($nucleo["id"] == $this->fIdNucleo)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$nucleo["id"]?>" <?=$sSel?>><?=$nucleo["nm_nucleo"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
						
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
