<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box widget-no-margin">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Cadastrar Sítio</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/sitio/cadastrar" name="" id="insere-altera" novalidate="novalidate">

                        <div class="control-group">
                            <label class="control-label">Nome do Sítio <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input name="fNmSitio" type="text" class="required">

                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Localidade <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdLocalidade" style="width: 200px;">
                                    <?php
                                    foreach ($this->vLocalidades as $localidade) {
                                        ?>
                                        <option value="<?=$localidade["id"]?>"><?=$localidade["nm_localidade"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Latitude <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input name="fLatitude" tabindex="1" type="text" class="required">
                                <input name="direcaoLatitude" value="norte" type="radio" class="required" style="margin: 0px;"> Norte
                                <input name="direcaoLatitude" value="sul" type="radio" class="required" style="margin: 0px;"> Sul
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Longitude <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input name="fLongitude" tabindex="1" type="text" class="required">
                                <input name="direcaoLongitude" value="leste" type="radio" class="required" style="margin: 0px;"> Leste
                                <input name="direcaoLongitude" value="oeste" type="radio" class="required" style="margin: 0px;"> Oeste
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Projeção <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdProjecao" style="width: 200px;">
                                    <?php
                                    foreach ($this->vProjecoes as $projecao) {
                                        ?>
                                        <option value="<?=$projecao["id"]?>"><?=$projecao["sistema_projecao"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box widget-no-margin">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
