
<h2>Sítios Cadastrados</h2>    
<?php
if ($this->vMenu == "") {
    
} else {
    foreach ($this->vMenu as $vModulo) {
        if ($vModulo["modulo"] == "Localidade") {
            ?>
            <ul class="nav nav-tabs">
                <?php
                foreach ($vModulo["programas"] as $vPrograma) {
                    if ($vPrograma['controller'] == "sitio") {
                        ?>
                        <li class="active">  
                        <?php } else {
                            ?>
                        <li> 
                            <?php
                        }
                        ?>
                        <a href="/<?= $vPrograma["controller"] . "/index" ?>"><?= $vPrograma["programa"] ?></a></li>
                    <?php
                }
                ?>
            </ul>
            <?php
        }
    }
}
?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="bs-example">
                <table class="tabela display" >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Sitio</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $value) {
                            ?>
                            <tr>
                                <td style="text-align: center;"><?php echo $value["id"]; ?></td>
                                <td style="text-align: center;"><?php echo $value["nm_sitio"]; ?></td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>