<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Cadastrar UF</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/unidade-medida/cadastrar" name="" id="insere-altera" novalidate="novalidate">
					
						<div class="control-group">
							<label class="control-label">Nome Do Metodo :<i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fUnidade" class="required">

							</div>
						</div>
                                            
                                            	<div class="control-group">
							<label class="control-label">Sigla :<i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fSigla" class="required">
							</div>
						</div>
                                            
               
                                            
						<div class="form-actions">
							<input type="hidden" name="sOP" value="cadastrar" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
