<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Nivel Taxonomico</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/nivel-taxonomico/alterar/nId/<?=$this->nId;?>" name="" id="insere-altera" novalidate="novalidate">
						<div class="control-group">
							<label class="control-label">Nivel Taxonomico <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fNivelTaxonomico" value="<?=$this->sNivelTaxonomico;?>" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Nivel Superior <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fNivelSuperior" value="<?=$this->sNivelSuperior;?>" class="required">
							</div>
						</div>
                                                <div class="control-group">
							<label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fNome" value="<?=$this->sNome;?>" class="required">
							</div>
						</div>
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="submit" value="Alterar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
