<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Senha</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="<?php echo $this->baseUrl();?>/alterar-senha/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
						<div class="control-group">
							<label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fNmUsuario" class="required" value="<?=$this->sNome?>">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">E-mail <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="2" type="text" name="fEmail"class="required" value="<?=$this->sEmail?>">

							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Grupo Usuário <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select enabled="false" tabindex="3" name="fIdGrupoUsuario" class="required" style="width: 200px;">
									<?php
									foreach ($this->vGrupoUsuario as $grupoUsuario) {
										if ($grupoUsuario["id"] == $this->nIdGrupo){
											$sSel = 'selected="selected"';
									?>
									<option value="<?=$grupoUsuario["id"]?>" <?=$sSel?>><?=$grupoUsuario["nm_grupo_usuario"]?></option>
									<?php }
									}
									?>
								</select>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Login <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" id="fLoginAlterar" name="fLoginAlterar" class="required" value="<?=$this->sLogin?>">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Senha <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="password" id="fSenha" name="fSenha" autocomplete="off">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Confirmar Senha <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="password" name="fSenhaConf" id="fSenhaConf" autocomplete="off">
							</div>
						</div>
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
