<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Atribuir Metodo para Protocolo</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/protocolos-metodos/cadastrar" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Protocolo <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name=fProtocolo value="<?= $this->fProtocolo; ?>" class="required">
                                <input type="hidden" name="fIdProtocolo" value="<?= $this->fIdProtocolo; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Protocolos Metodos <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select id="fMetodos" name="fMetodos[]" multiple="multiple">

                                    <?php
                                    foreach ($this->vMetodo as $metodos) {
                                        if (array_search($metodos["id"], $this->vProtocolosMetodos)) {
                                            ?>
                                            <option value="<?= $metodos["id"]; ?>" selected="selected"><?= $metodos["nm_metodo"] ?></option>
                                            <?php
                                        } else {
                                            ?>
                                            <option value="<?= $metodos["id"]; ?>"><?= $metodos["nm_metodo"] ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>

                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
