<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
                                        <h5>Cadastrar Identifica&ccedil;&atilde;o</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/sub-amostra/cadastrar" name="" id="insere-altera" novalidate="novalidate">
					    
                                                <div class="control-group">
							<label class="control-label">Taxon <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fIdTaxon" class="required" style="width: 400px;">
									<?php
									foreach ($this->vTaxon as $taxon) {
									?>
									<option value="<?=$taxon["id"]?>"><?=$taxon["taxon"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                            
                                                 <div class="control-group">
							<label class="control-label">Amostra <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fIdAmostra" class="required" style="width: 400px;">
									<?php
									foreach ($this->vAmostra as $Amostra) {
									?>
									<option value="<?=$Amostra["id"]?>"><?=$Amostra["id"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                    
                                         
                                                <div class="control-group">
							<label class="control-label">Quantidade: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fQuantidade" style="width: 400px">
							</div>
						</div>
                                            
                                           
                                            
                                                   <div class="control-group">
							<label class="control-label">Status<i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fStatus_2" class="required" style="width: 400px;">
								<option value="1">Ativo</option>
                                                                <option value="0">Inativo</option>
								</select>
							</div>
						</div>
                                            
                                            
                                            <div class="control-group">
							<label class="control-label">Quantidade de Machos: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fQtMachos" style="width: 400px">
							</div>
						</div>
                                            
                                            <div class="control-group">
							<label class="control-label">Quantidade de Femeas: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fQtFemeas" style="width: 400px">
							</div>
						</div>
                                            
						<div class="form-actions">
							<input type="hidden" name="sOP" value="cadastrar" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
