<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Alterar Usuário</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/usuario/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fNmUsuario" class="required" value="<?=$this->sNome?>">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">E-mail :</label>
                            <div class="controls">
                                <input tabindex="2" type="text" name="fEmail" value="<?=$this->sEmail?>">

                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Grupo Usuário :</label>
                            <div class="controls">
                                <select tabindex="3" name="fIdGrupoUsuario"  style="width: 200px;">
                                    <?php
                                    foreach ($this->vGrupoUsuario as $grupoUsuario) {
                                        if ($grupoUsuario["id"] == $this->nIdGrupo)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$grupoUsuario["id"]?>" <?=$sSel?>><?=$grupoUsuario["nm_grupo_usuario"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>



                        <div class="control-group">
                            <label class="control-label">Instituição :</label>
                            <div class="controls">
                                <select tabindex="3" name="fIdInstituicao"  style="width: 200px;">
                                    <?php
                                    foreach ($this->vInstituicao as $instituicao) {
                                        if ($instituicao["id"] == $this->nIdInstituicao)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$instituicao["id"]?>" <?=$sSel?>><?=$instituicao["razao_social"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Maior Titulação :</label>
                            <div class="controls">
                                <select tabindex="3" name="fIdTitulacao"  style="width: 200px;">
                                    <?php
                                    foreach ($this->vTitulacao as $titulacao) {
                                        if ($titulacao["id"] == $this->nIdTitulacao)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$titulacao["id"]?>" <?=$sSel?>><?=$titulacao["nm_titulacao"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Protocolo :</label>
                            <div class="controls ">
                                <select name="fIdProtocolo" style="width: 200px;">
                                    <?php
                                    foreach ($this->vProtocolo as $protocolo) {
                                        if ($protocolo["id"] == $this->nIdProtocolo)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$protocolo["id"]?>" <?=$sSel?>><?=$protocolo["nm_protocolo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Núcleo :</label>
                            <div class="controls ">
                                <select id="fIdNucleo" name="fIdNucleo[]" multiple="multiple" style="width: 200px;">
                                    <?php
                                    foreach ($this->vNucleos as $nucleo) {
                                        ?>
                                    <option value="<?=$nucleo["id"];?>" <?=$nucleo["selected"]?>><?=$nucleo["nm_nucleo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Login <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" id="fLogin" name="fLogin" class="required" value="<?=$this->sLogin?>">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Senha <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="password" id="fSenha" name="fSenha" autocomplete="off" value="<?=$this->sSenha?>">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Confirmar Senha <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="password" name="fSenhaConf" id="fSenhaConf" autocomplete="off" value="<?=$this->sSenha?>">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Data Entrada: </label>
                            <div class="controls">
                                <input type="text" name="fDatadeCadastro" data-date-format="dd-mm-yyyy" value="<?=UtilsDate::formataDataToShow($this->sDtCadastro)?>" class="datepicker" />
                            </div>
                        </div>

                        <!--	<div class="control-group">
                                 <label class="control-label">Somente caso seja EGRESSO:</label>
                                 <div class="controls">
                                  <input type="checkbox" id="fcheckflag" name="fcheckflag" checked="checked" >
 </div>
                 </div> -->


                        <div class="control-group">
                            <label class="control-label">Data Saida: </label>
                            <div class="">
                                <input id="dataSaida" disabled="true" type="text" name="fDtSaida" data-date-format="dd-mm-yyyy"  clear-btn="true" force-parse="false" value="<?=UtilsDate::formataDataToShow($this->sDtSaida)?>" class="datepicker" />
                                <div class="controls">
                                    <input type="checkbox" id="fcheckflag" name="fcheckflag"  >
                                    <label class="control-label">Somente caso seja EGRESSO:</label>
                                </div>
                            </div>
                        </div>

                        <script>
                            /*  if( $("[id='fcheckflag']").prop('checked') ){
$("[id='dataSaida']").prop('disabled', false);
                        }else{
                                 $("[id='dataSaida']").prop('disabled', true);
                        }*/

                            $("[id='fcheckflag']").change(function() {
                                //$("[id='dataSaida']").attr('disabled',! this.checked)
                                if( $("[id='fcheckflag']").prop('checked') ){
                                    $("[id='dataSaida']").prop('disabled', false);
                                }else{
                                    $("[id='dataSaida']").prop('disabled', true);
                                }
                            });
                        </script>

                        <div class="control-group">
                            <label class="control-label">Citação:</label>
                            <div class="controls">
                                <input type="text" id="fCitacao" name="fCitacao" value="<?=$this->sCitacao?>">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">RG:</label>
                            <div class="controls">
                                <input type="text" id="fRg" name="fRg" value="<?=$this->sRg?>">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Cpf:</label>
                            <div class="controls">
                                <input type="text" id="fCpf" name="fCpf" value="<?=$this->sCpf?>">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Sisbio:</label>
                            <div class="controls">
                                <input type="text" id="fSisbio" name="fSisbio" value="<?=$this->sSisbio?>">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Lattes:</label>
                            <div class="controls">
                                <input type="text" id="fLattes" name="fLattes" value="<?=$this->sLattes?>">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Banco:</label>
                            <div class="controls ">
                                <select name="fIdBanco" style="width: 200px;">
                                    <?php

                                    function debug_to_console($data) {
                                        if (is_array($data) || is_object($data)) {
                                            echo("<script>console.log('PHP: " . json_encode($data) . "');</script>");
                                        } else {
                                            echo("<script>console.log('PHP: " . $data . "');</script>");
                                        }
                                    }

                                    $aux = $this->nIdBanco;
                                    debug_to_console($this->nIdBanco);
                                    debug_to_console("ESTOU AQUI");
                                    foreach ($this->vBanco as $banco) {
                                        if ($banco["id"] == $this->nIdBanco)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$banco["id"]?>" <?=$sSel?>><?=$banco["nm_banco"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Banco Agencia:</label>
                            <div class="controls">
                                <input type="text" id="fBancoAgencia" value="<?=$this->sBancoAgencia?>" name="fBancoAgencia">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Banco Conta:</label>
                            <div class="controls">
                                <input type="text" id="fBancoConta" value="<?=$this->sBancoConta?>" name="fBancoConta">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Bolsista:</label>
                            <div class="controls">

                                <?php
                                if ($this->sBolsista == true) {
                                    $checked = 'checked="checked" ';
                                } else {
                                    $checked = "";
                                }
                                ?>
                                <input type="checkbox" id="fVinculoEmpregaticio" name="fBolsista"  <?php echo $checked; ?>>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Vinculo Empregaticio:</label>
                            <div class="controls">

                                <?php
                                if ($this->sVinculoEmpregaticio == true) {
                                    $checked = 'checked="checked" ';
                                } else {
                                    $checked = "";
                                }
                                ?>
                                <input type="checkbox" id="fVinculoEmpregaticio" name="fVinculoEmpregaticio"  <?php echo $checked; ?>>
                            </div>
                        </div>





                        <div class="control-group">
                            <label class="control-label">Outros:</label>
                            <div class="controls">
                                <input type="text" id="fOutro" value="<?=$this->sOutro?>" name="fOutro">
                            </div>
                        </div>



                        <input type="hidden" name="fDtUtimaAtualizacao" data-date-format="dd-mm-yyyy" value="<?php echo date("d-m-Y") ?>" class="datepicker" />

                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="alterar" />
                            <input type="hidden" name="nId" value="<?=$this->nId?>" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
