<h2>Usuarios Cadastrados</h2>    
<?php
if ($this->vMenu == "") {
    
} else {
    foreach ($this->vMenu as $vModulo) {
        if ($vModulo["modulo"] == "Segurança") {
            ?>
            <ul class="nav nav-tabs">
                <?php
                foreach ($vModulo["programas"] as $vPrograma) {
                    if ($vPrograma['controller'] == "usuario") {
                        ?>
                        <li class="active">  
                    <?php } else {
                        ?>
                        <li> 
                            <?php
                        }
                        ?>
                        <a href="/<?= $vPrograma["controller"] . "/index" ?>"><?= $vPrograma["programa"] ?></a></li>
                        <?php
                    }
                    ?>
            </ul>
                <?php
            }
        }
    }
    ?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="bs-example">
                <table class="tabela display" >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Login</th>
                            <th>Grupo</th>
                        </tr>
                    </thead>

                    <tbody>

<?php foreach ($this->paginator as $value) {
    ?>
                            <tr>
                                <td><?php echo $value["id"]; ?></td>
                                <td><?php echo $value["nm_usuario"]; ?></td>
                                <td><?php echo $value["login"]; ?></td>
                                <td><?php echo $value["nm_grupo_usuario"]; ?></td>
                            </tr>
<?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
