<?php
/*
* Jhonny Scerni Gondim Costa
* Criando e exportando planilhas do Excel

*/

// Definimos o nome do arquivo que será exportado

$arquivo = 'relatorio_excel_protocolo_expedicao'.date("d/m/Y").".xls";



// Configurações header para forçar o download

header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");

header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");

header ("Cache-Control: no-cache, must-revalidate");

header ("Pragma: no-cache");

header ("Content-type: application/x-msexcel");

header ("Content-Disposition: attachment; filename=\"{$arquivo}\"" );

header ("Content-Description: PHP Generated Data" );

// Envia o conteúdo do arquivo

?>


<div class="widget-content nopadding">
    
    <h2> Quantidade de Protocolos e Expedi&ccedil;&otilde;es no Sinbio </h1>
    <table border="1" style="border: 1px solid #cccccc;margin-bottom:1px; margin-left: 20px; margin-right: 20px;">
       
        <th>Sigla</th>
        <th>Expedicao</th>
        
       
<?php 
$anterior = "";
$contprotocolo = 0;
$contexpedicao = 0;
foreach($this->dadosRel as $value){ ?>
        <tr> 
            
              <?php 
        
        if ($value['sigla'] != $anterior){ ?></php>
           
        <?php 
         $anterior = $value['sigla'];
         $contprotocolo ++;
        } ?>
            <td><div style="text-align: center;"><?= $value['sigla'] ?></div></td>
            <td><div style="text-align: center"><?= $value['id'] ?></div></td>
           
            
         </tr>
             
                 <?php $contexpedicao++; }?>
            
         
</table >
    
    <table border="1">
        <tr>
            <td colspan="2"> &ensp; </td>
        </tr>
        <tr>                                  
            <td colspan="2"> <div> Quantidade de  Protocolo : <?php echo $contprotocolo; ?></div> </td>                           
        </tr>
        <tr>
            <td colspan="2"><div> Quantidade de Expedi&ccedil;&atilde;o : <?php echo $contexpedicao; ?></div></td>                                
        </tr>	
    </table>			
				
						
                            </div>