<?php
/*
* Jhonny Scerni Gondim Costa
* Criando e exportando planilhas do Excel

*/

// Definimos o nome do arquivo que será exportado

$arquivo = 'relatorio_excel_amostra_'.date("d/m/Y").".xls";



// Configurações header para forçar o download

header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");

header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");

header ("Cache-Control: no-cache, must-revalidate");

header ("Pragma: no-cache");

header ("Content-type: application/x-msexcel");

header ("Content-Disposition: attachment; filename=\"{$arquivo}\"" );

header ("Content-Description: PHP Generated Data" );

// Envia o conteúdo do arquivo

?>


<div class="widget-content nopadding">
    
   
    <table border="1" style="border: 1px solid #cccccc;margin-bottom:1px; margin-top: 20px; margin-left: 20px; margin-right: 20px;">
        <th>&ensp;</th>
        <th>id_amostra_coletor</th>
        <th>projeto_programa</th>
        <th>protocolo</th>
        <th>metodo</th>
        <th>sitio</th>
        <th>latitude</th>
        <th>longitude</th>
        
       
<?php 
$cont = 1;
foreach($this->dadosRel as $value){ ?>
        <tr> 
            <td><div style="text-align: center;"><?= $cont ?></div></td>
            <td><div style="text-align: center"><?= $value['id_amostra_coleta'] ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_projeto_programa']) ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_protocolo']) ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_metodo']) ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_sitio']) ?></div></td>
            <td><div style="text-align: center"><?= $value['latitude'] ?></div></td>
            <td><div style="text-align: center"><?= $value['longitude'] ?></div></td>
            
         </tr>
             
                 <?php $cont++; }?>
                    
</table>
    
   
                                            
                                          
				
				
						
                            </div>