<?php
/*
* Jhonny Scerni Gondim Costa
* Criando e exportando planilhas do Excel

*/

// Definimos o nome do arquivo que será exportado

$arquivo = 'relatorio_excel_Sisbio_'.date("d/m/Y").".xls";



// Configurações header para forçar o download

header ("Expires: Mon, 26 Jul 1997 05:00:00 GMT");

header ("Last-Modified: " . gmdate("D,d M YH:i:s") . " GMT");

header ("Cache-Control: no-cache, must-revalidate");

header ("Pragma: no-cache");

header ("Content-type: application/x-msexcel");

header ("Content-Disposition: attachment; filename=\"{$arquivo}\"" );

header ("Content-Description: PHP Generated Data" );

// Envia o conteúdo do arquivo

?>


<div class="widget-content nopadding">
    <?
    	if(count($this->dadosRel) > 0){
    ?>
    <table border="1" style="border: 1px solid #cccccc;margin-bottom:1px; margin-top: 20px; margin-left: 20px; margin-right: 20px;">
         <th>&ensp;</th>
        <th>id_amostra_coletor</th>
        <th>Coletor(es)</th>
        <th>Data Coleta</th>
        <th>Hora Coleta</th>
        <th>Local</th>
        <th>latitude</th>
        <th>Dire&ccedil;&atilde;o_Latitude</th>
        <th>longitude</th>
        <th>Dire&ccedil;&atilde;o_Logitude</th>
        <th>Trilha</th>
        <th>Dist&acirc;ncia da Trilha</th>
        <th>Parcela</th>
        <th>Dist&acirc;ncia da parcela</th>
        <th>Tipo de Armadilha</th>
        <th>Altura da Armadilha/Subst.</th>
        <th>Atrativo</th>
        <th>Densidade de sub-bosque</th>
        <th>Temperatura do Ar</th>
        <th>Umidade do Ar</th>
        <th>Abertura de Dossel</th>
        <th>Tipo de substrato</th>
        <th>Determinador</th>
        <th>Data de Determina&ccedil;&atilde;o</th>
        <th>Data de Referencia</th>
        <th>Observa&ccedil;&atilde;o</th>
        
        <th>Ordem</th>
        <th>Familia</th>
        <th>Sub-Familia</th>
        <th>Genero</th>
        <th>Sub-Genero</th>
        <th>Grupo-Especie</th>
        <th>Taxon</th>
        <th>Morfoesp&eacute;cie</th>
        <th>Quantidade de Indiv&iacute;duos</th>
        
        <th>Abundancia de Femeas</th>
        <th>Abundancia de Machos</th>
        <th>Conserva&ccedil;&atilde;o</th>
        <th>Destina&ccedil;&atilde;o</th>
        
        


        
        
       
<?php 
$cont = 1;
foreach($this->dadosRel as $value){ ?>
        <tr> 
            <td><div style="text-align: center"><?= $cont ?></div></td>
            <td><div style="text-align: center"><?= $value['id_amostra_coleta'] ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_usuario']) ?></div></td>
             <td><div style="text-align: center"><?= $value['data_coleta'] ?></div></td>
              <td><div style="text-align: center"><?= $value['hora_coleta'] ?></div></td>
            <td><div style="text-align: center"><?= utf8_decode($value['nm_sitio']) ?></div></td>
            <td><div style="text-align: center"><?= $value['latitude'] ?></div></td>
            <td><div style="text-align: center"><?= $value['direcao_latitude'] ?></div></td>           
            <td><div style="text-align: center"><?= $value['longitude'] ?></div></td>
            <td><div style="text-align: center"><?= $value['direcao_longitude'] ?></div></td>
            <td><div style="text-align: center">&ensp;</div></td>
            <td><div style="text-align: center">&ensp;</div></td>
            <td><div style="text-align: center">&ensp;</div></td>
            <td><div style="text-align: center">&ensp;</div></td>
            <td><div style="text-align: center"><?= $value['nm_metodo'] ?></div></td>
            <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center"><?= $value['nm_atrativos'] ?></div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center"><?= $value['data_determinacao'] ?></div></td>
             <td><div style="text-align: center"><?= $value['referencia_taxon'] ?></div></td>
             <td><div style="text-align: center"><?= $value['taxon_observacao'] ?></div></td>
             
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             <td><div style="text-align: center">&ensp;</div></td>
             
             
             <td><div style="text-align: center"><?= $value['femea'] ?></div></td>
             <td><div style="text-align: center"><?= $value['machos'] ?></div></td>
             <td><div style="text-align: center"><?= $value['conservacao_material'] ?></div></td>
             <td><div style="text-align: center"><?= $value['nm_destinacao'] ?></div></td>
            
            
         </tr>
             
                 <?php $cont++; }?>
                    
</table>
    
    <?php } else { ?>
    <div style="padding: 20px 0 0 50px; font-size: 15px; font-weight: bold; color: #666666;">
        Nenhum Resultado Encontrado
    </div>
    <?php }?>
                                            
                                          
				
				
					

                            </div>
			