<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
                                        <h5>Alterar Vari&aacute;vel</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/variaveis/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
						
					
                                            
                                            <div class="control-group">
							<label class="control-label">Unidade de Medida <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fIdUnidade" class="required" style="width: 200px;">
									<?php
									foreach ($this->vUnidade as $unidademedida) {
                                                                            if ($unidademedida["id"] == $this->nIdUnidadeMedida)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$unidademedida["id"]?>" <?=$sSel?>><?=$unidademedida["nm_unidade"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                           
                                            
                                          
                                               <div class="control-group">
							<label class="control-label">Nome da Variavel: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fNmVariavel" value="<?=$this->sNmVariavel?>" style="width: 400px">
							</div>
						</div>
                                            
                                             <div class="control-group">
							<label class="control-label">Descrição: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fDescricao" value="<?=$this->sDescricao?>" style="width: 400px">
							</div>
						</div>
                                            
                                                  
                                               <div class="control-group">
							<label class="control-label">Sequ&ecirc;ncia :</label>
							<div class="controls">
								<select name="fOrdem"  style="width: 400px;">
                                                                    <option value="0">Ordem de entrada da vari&aacute;vel na planilha</option>
                                                                        <option value="1">Ordem <?=$this->sOrdem?></option>
									<option value="1">Ordem 1</option>
                                                                        <option value="2">Ordem 2</option>
                                                                        <option value="3">Ordem 3</option>
                                                                        <option value="4">Ordem 4</option>
                                                                        <option value="5">Ordem 5</option>
                                                                        
									
								</select>
							</div>
						</div>
                                            
                                               <div class="control-group">
							<label class="control-label">Nivel <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fNivelAmostra" class="required" style="width: 400px;">
									<option value="1">Nivel <?=$this->sNivelAmostra?></option>
									<option value="1">Nivel 1</option>
                                                                        <option value="2">Nivel 2</option>
                                                                        <option value="3">Nivel 3</option>
                                                                        <option value="4">Nivel 4</option>
                                                                        <option value="5">Nivel 5</option>
									
								</select>
							</div>
						</div>
                                            
                                              <div class="control-group">
							<label class="control-label">Obrigatorio <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fObrigatorio" class="required" style="width: 400px;">
									<option value="1"><?php if($this->sObrigtorio == 1){ echo "SIM";}else{ echo "NÃO";} ?></option>
									<option value="1">SIM</option>
                                                                        <option value="0">NÃO</option>
									
								</select>
							</div>
						</div>
                                            
						 <div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
