<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
                                        <h5>Cadastrar Vari&aacute;vel</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/variaveis/cadastrar" name="" id="insere-altera" novalidate="novalidate">
						
                                            
                                            <div class="control-group">
							<label class="control-label">Unidade de Medida <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fIdUnidadeMedida" class="required" style="width: 400px;">
									<?php
									foreach ($this->vUnidade as $unidademedida) {
									?>
									<option value="<?=$unidademedida["id"]?>"><?=$unidademedida["nm_unidade"]?> - <?=$unidademedida["sigla"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                         
                                            
                                            
                                            <div class="control-group">
							<label class="control-label">Nome da Variavel: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fNmVariavel" style="width: 400px">
							</div>
						</div>
                                            
                                             <div class="control-group">
							<label class="control-label">Descrição: </label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fDescricao" style="width: 400px">
							</div>
						</div>
                                            
                                               <div class="control-group">
                                                   <label class="control-label">Sequ&ecirc;ncia: <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fOrdem" class="required" style="width: 400px;">
									<option value="0">--Ordem de entrada da vari&aacute;vel na planilha--</option>
									<option value="1">Ordem 1</option>
                                                                        <option value="2">Ordem 2</option>
                                                                        <option value="3">Ordem 3</option>
                                                                        <option value="4">Ordem 4</option>
                                                                        <option value="5">Ordem 5</option>
									
								</select>
							</div>
						</div>
                                            
                                               <div class="control-group">
							<label class="control-label">Nivel <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fNivelAmostra" class="required" style="width: 400px;">
									<option value="0">--Selecione a Nivel--</option>
									<option value="1">Nivel 1</option>
                                                                        <option value="2">Nivel 2</option>
                                                                        <option value="3">Nivel 3</option>
                                                                        <option value="4">Nivel 4</option>
                                                                        <option value="5">Nivel 5</option>
									
								</select>
							</div>
						</div>
                                            
                                              <div class="control-group">
							<label class="control-label">Obrigatorio <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fObrigatorio" class="required" style="width: 400px;">
									<option>--Selecione a Obrigatoriedade--</option>
									<option value="1">SIM</option>
                                                                        <option value="0">NÃO</option>
									
								</select>
							</div>
						</div>
                                            
						<div class="form-actions">
							<input type="hidden" name="sOP" value="cadastrar" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
