<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Protocolo</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/protocolo/alterar/nId/<?=$this->nId;?>" name="" id="insere-altera" novalidate="novalidate">
							<div class="control-group">
							<label class="control-label">Sigla <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fSigla" value="<?=$this->sNmSigla;?>" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Nome Do Protocolo <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fProtocolo" value="<?=$this->sNmProtocolo;?>" class="required">

							</div>
						</div>
                                            			<div class="control-group">
							<label class="control-label">Descrição </label>
							<div class="controls">
								<input type="text" name="fDescricao" value="<?=$this->sDescricao;?>" >

							</div>
						</div>
                                            
                                            	<div class="control-group">
							<label class="control-label">Cordenador de Protocolo<i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select tabindex="3" name="fIdUsuario" class="required" style="width: 200px;">
									<?php
									foreach ($this->vUsuario as $usuario) {
										if ($usuario["id"] == $this->nIdUsuario)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$usuario["id"]?>" <?=$sSel?>><?=$usuario["nm_usuario"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="submit" value="Alterar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
