<?= $this->doctype() ?>
<html lang="en">
<head>
	<title>Painel de Controle</title>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="/css/sinbio/bootstrap.min.css" />
	<link rel="stylesheet" href="/css/sinbio/bootstrap-responsive.min.css" />
	<link rel="stylesheet" href="/css/sinbio/style.css" />
	<link rel="stylesheet" href="/css/sinbio/media.css" class="skin-color" />
	<link rel="stylesheet" href="/css/sinbio/colorpicker.css" />
	<link rel="stylesheet" href="/css/sinbio/datepicker.css" />
	<link rel="stylesheet" href="/css/sinbio/uniform.css" />
	<link rel="stylesheet" href="/css/sinbio/select2.css" />		
	<link rel="stylesheet" href="/plugin/jquery.alerts/jquery.alerts.css" />
	<?=$this->layout()->includeCss?>
        
        
        
       
</head>

    <body>

        <!--Header-part-->
        <div id="header">
        </div>
        <!--close-Header-part-->

        <!--top-Header-messaages-->
        <div class="btn-group rightzero">
            <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a>
            <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i> </a>
            <a class="top_message tip-bottom" title="Manage Comments">
                <i class="icon-comment"></i>
                <span class="label label-important">5</span>
            </a>
            <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a>
        </div>
        <!--close-top-Header-messaages-->

        <!--top-Header-menu-->
        <div id="user-nav" class="navbar navbar-inverse">
            <ul class="nav">
                <li class="">
                    <!--				<a title="" href="#">
                                                            <i class="icon icon-user"></i>
                                                            <span class="text">Profile</span>
                                                    </a>-->
                </li>

<!--                <li class="">
                    <a title="" href="/sinbio/login/logoff">
                        <i class="icon icon-share-alt"></i>
                        <span class="text">Logout</span>
                    </a>
                </li>-->
            </ul>
        </div>
        <!--close-top-Header-menu-->


      	
	<!-- MENU -->


      	<div id="content">
	
		<?=$this->layout()->content;?>
	</div>
	<div class="row-fluid">
		<div id="footer" class="span12">Powered by <a href="#"></a></div>
	</div>
    </body>
<script src="/js/jquery-1.7.1.min.js"></script>
<script src="/js/geral/jquery.min.js"></script>
<script src="/js/geral/jquery.ui.custom.js"></script>
<script src="/js/geral/bootstrap.min.js"></script>
<script src="/js/geral/bootstrap-colorpicker.js"></script>
<script src="/js/geral/bootstrap-datepicker.js"></script>
<script src="/js/geral/jquery.uniform.js"></script>
<script src="/js/geral/select2.min.js"></script>
<script src="/js/geral/maruti.js"></script>
<script src="/js/geral/maruti.form_common.js"></script>
<script src="/plugin/jquery.alerts/jquery.alerts.js"></script>
<?=$this->layout()->includeJs?>
</html>



