<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box widget-no-margin">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Cadastrar Localidade</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/localidade/cadastrar" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fNmLocalidade" class="required">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Município <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdMunicipio" style="width: 200px;">
                                    <?php
                                    foreach ($this->vMunicipio as $municipio) {
                                        ?>
                                        <option value="<?=$municipio["id"]?>"><?=$municipio["nm_municipio"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Latitude <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" class="required"  name="flatitude">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Longitude <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" class="required" name="flongitude">
                            </div>
                        </div>



                        <div class="control-group">
                            <label class="control-label">Núcleo :</label>
                            <div class="controls ">
                                <select name="fIdNucleo" style="width: 400px;">
                                    <?php
                                    foreach ($this->vNucleo as $nucleo) {
                                        ?>
                                        <option value="<?=$nucleo["id"]?>"><?=$nucleo["nm_nucleo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>


                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box widget-no-margin">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
