<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Alterar Amostra</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="<?php echo $this->baseUrl(); ?>/amostra/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Id Amostra Projeto: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fidAmostraProjeto" value="<?php echo $this->sIdAmostraProjeto ?>" style="width: 400px">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">C&oacute;digo Amostra/C&oacute;digo Amostra/N&#186; Coletor <i class="icon-asterisk"></i>: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fIdAmostraColeta" class="required" value="<?php echo $this->sIdAmostraColeta ?>" style="width: 400px">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Data Coleta: </label>
                            <div class="controls">
                                <input type="text" name="fDataColeta" data-date-format="dd/mm/yyyy" value="<?php echo UtilsDate::formataDataToShow($this->sDtColeta) ?>"
                                       class="datepicker" readonly="true" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Hora Coleta <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select name="fHoraColeta" class="required" style="width: 400px;">

                                    <option value="<?php echo $this->sHoraColeta ?>"><?php echo $this->sHoraColeta ?></option>
                                    <option value="00:00:00">00:00:00</option>
                                    <option value="01:00:00">01:00:00</option>
                                    <option value="02:00:00">02:00:00</option>
                                    <option value="03:00:00">03:00:00</option>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Latitude: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fLatitude" value="<?php echo $this->sLatitude ?>" style="width: 400px">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Longitude: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fLongitude" value="<?php echo $this->sLongitude ?>" style="width: 400px">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Protocolo <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select name="fIdProtocolo" class="required" style="width: 400px;">
                                    <?php
                                    foreach ($this->vProtocolo as $protocolo) {

                                        if ($protocolo["id"] == $this->nIdProtocolo)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$protocolo["id"]?>" <?=$sSel?>><?=$protocolo["sigla"]?> - <?=$protocolo["nm_protocolo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">M&eacute;todos <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select name="fIdMetodos" class="required" style="width: 400px;">
                                    <?php
                                    foreach ($this->vMetodo as $Metodo) {
                                        if ($Metodo["id"] == $this->nIdMetodo)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$Metodo["id"]?>" <?=$sSel?>><?=$Metodo["nm_metodo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Atrativos :</label>
                            <div class="controls">
                                <select name="fIdAtrativos" style="width: 400px;">
                                    <?php
                                    foreach ($this->vAtrativos as $Atrativos) {

                                        if ($Atrativos["id"] == $this->nIdAtrativos)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$Atrativos["id"]?>" <?=$sSel?>><?=$Atrativos["nm_atrativos"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Expedi&ccedil;&atilde;o  <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select name="fIdExpedicao" class="required" style="width: 400px;">
                                    <?php
                                    foreach ($this->vExpedicao as $Expedicao) {

                                        if ($Expedicao["id"] == $this->nIdExpedicao)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$Expedicao["id"]?>"> <?= $Expedicao["nm_sitio"] ?> - <?= $Expedicao["data_inicio"] ?> </option>

                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Direção Latitude: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fDirecaoLatitude" value="<?php echo $this->sDirecaoLatitude ?>" style="width: 400px">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Direção Longitude: </label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fDirecaoLongitude" value="<?php echo $this->sDirecaoLongitude ?>"   style="width: 400px">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Proje&ccedil;&atilde;o <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select name="fIdProjecao" class="required" style="width: 400px;">
                                    <?php
                                    foreach ($this->vProjecao as $Projecao) {

                                        if ($Projecao["id"] == $this->nIdProjecao)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$Projecao["id"]?>" <?=$sSel?>><?=$Projecao["sistema_projecao"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Conserva&ccedil;&atilde;o :</label>
                            <div class="controls">
                                <select name="fIdConservacao"  style="width: 400px;">
                                    <?php
                                    foreach ($this->vConservacao as $Conservacao) {

                                        if ($Conservacao["id"] == $this->nIdConservacao)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$Conservacao["id"]?>" <?=$sSel?>><?=$Conservacao["conservacao_material"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Destina&ccedil;&atilde;o :</label>
                            <div class="controls">
                                <select id="fIdDestinacao" name="fIdDestinacao[]" multiple="multiple" style="width: 400px;">
                                    <?php
                                    foreach ($this->vDestinacoes as $destinacao) {
                                        ?>
                                        <option value="<?=$destinacao["id"]?>" <?=$destinacao["selected"]?>><?=$destinacao["nm_destinacao"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="alterar" />
                            <input type="hidden" name="nId" value="<?=$this->nId?>" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
