
<h2>Amostras Cadastradas</h2>    
<?php
if ($this->vMenu == "") {
    
} else {
    foreach ($this->vMenu as $vModulo) {
        if ($vModulo["modulo"] == "Amostra") {
            ?>
            <ul class="nav nav-tabs">
                <?php
                foreach ($vModulo["programas"] as $vPrograma) {


                    if ($vPrograma['controller'] == "amostra") {
                        ?>
                        <li class="active">  
                    <?php } else {
                        ?>
                        <li> 
                            <?php
                        }
                        ?>
                        <a href="/<?= $vPrograma["controller"] . "/index" ?>"><?= $vPrograma["programa"] ?></a></li>
                        <?php
                    }
                    ?>
            </ul>
                <?php
            }
        }
    }
    ?>

<!--<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <table class="grid" style="display: none"></table>
        </div>
    </div>
</div>-->

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="bs-example">
                <table class="tabela display" >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Código Amostra</th>
                            <th>Protocolo</th>
                            <th>Método</th>
                            <th>Expedição</th>
                        </tr>
                    </thead>

                    <tbody>

<?php foreach ($this->paginator as $value) {
    ?>
                            <tr>
                                <td style="text-align: center;"><?php echo $value["id"]; ?></td>
                                <td style="text-align: center;"><?php echo $value["codigo_amostra_numero_coletor"]; ?></td>
                                <td style="text-align: center;"><?php echo $value["nm_protocolo"]; ?></td>
                                <td style="text-align: center;"><?php echo $value["nm_metodo"]; ?></td>
                                <td style="text-align: center;"><?php echo $value["data_inicio"] . ' - ' . $value["nm_localidade"]; ?></td>
                            </tr>
<?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>