<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Módulo</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/metodo/alterar/nId/<?=$this->nId;?>" name="" id="insere-altera" novalidate="novalidate">
							<div class="control-group">
							<label class="control-label">Sigla <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fSigla" value="<?=$this->sNmSigla;?>" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Nome Do Metodo <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fMetodo" value="<?=$this->sNmMetodo;?>" class="required">

							</div>
						</div>
                                            			<div class="control-group">
							<label class="control-label">Descrição </label>
							<div class="controls">
								<input type="text" name="fDescricao" value="<?=$this->sDescricao;?>" >

							</div>
						</div>
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="submit" value="Alterar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
