<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Alterar Permissões</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/participantes-expedicao/cadastrar" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Expedicao <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name=fExpedicao value="<?= $this->fExpedicao; ?>" class="required">
                                <input type="hidden" name="fIdExpedicao" value="<?= $this->fIdExpedicao; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"> Usuarios Participantes <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select id="fUsuarios" name="fUsuarios[]" multiple="multiple">
                                  <?php
                                            foreach ($this->vUsuario as $usuario) {
                                                if (array_search($usuario["id"], $this->vParticipantesExpedicao)) {
                                                    ?>
                                                    <option value="<?= $usuario["id"]; ?>" selected="selected"><?= $usuario["nm_usuario"] ?></option>
                                                    <?php
                                                } else {
                                                    ?>
                                                    <option value="<?= $usuario["id"]; ?>"><?= $usuario["nm_usuario"] ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                   
                                </select>

                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
