<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title> Sinbio - Sistemas de inventário biológicos da Amazônia</title>
<link rel="stylesheet/less" href="/css/styles.less" type="text/css" >
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script src="/js/modernizr.js"></script>

<script src="<?php echo $this->baseUrl() . "/js/less-1.4.1.min.js" ?>" type="text/javascript"></script>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="<?php echo $this->baseUrl() . "/js/bootstrap.min.js" ?>"></script>


<link rel="stylesheet" href="/css/sinbio/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="/css/sinbio/login.css" />
<link rel="stylesheet" href="/plugin/jquery.alerts/jquery.alerts.css" />
<script src="/js/jquery-1.7.1.min.js"></script>
<script src="/js/sinbio/login.js"></script>
<script src="/plugin/jquery.alerts/jquery.alerts.js"></script>

<!--[if lt IE 9]>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>

<body>



    <div class="selos">
        <a href="" class="brasil">brasil</a>
        <a href="" class="acesso">acesso à informação</a>  
    </div>
 

    <div class="head">



        <div class="carousel hidden-phone">
            <div id="myCarousel" class="carousel slide">
               
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="/images/pictures/1.jpg" width="100%">
                        <div class="carousel-caption">
                        </div>
                    </div>
		    <div class="item">
                        <img src="/images/pictures/2.jpg" width="100%">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img src="/images/pictures/3.jpg" width="100%">
                        <div class="carousel-caption">
                        </div>
                    </div>
		    <div class="item">
                        <img src="/images/pictures/4.jpg" width="100%">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div> <!-- Carousel-inner-->

		<a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            </div>
        </div> <!-- carousel -->

         <div class="header row-fluid">
            
                <div class="span4 divlogo">
                    <div class="logo">
                        <a href="#"><img src="/images/logo.png"></a>
                    </div>
                </div>
                
                <div class="mmenu">
                <div class="span8 menu">
                    <div class="navbar navbar-inverse ">
                      <div class="navbar-inner">
                        <div class="container-fluid">
                          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>

                          <div class="nav-collapse collapse">
                            <ul class="nav">
                              <li><a href="#oque">O que é Sinbio?</a></li>
                              <li><a href="#comofunciona">Como funciona?</a></li>
                              <li><a href="#contact">Contato</a></li>
                            </ul>
                          </div><!--/.nav-collapse -->
                        </div><!--/.nav-fluid -->
                      </div> <!--/.nav-inner -->
                    </div><!--/.navbar -->

                        <div class="span6 offset3">

                            <form class="form" method="post" action="<?php echo $this->baseUrl();?>/login/processa" id="loginform">
                                <div class="pull-right">
                                <a href="">Login</a>
                                <a href="" class='btsimbio'>SINBio</a>
                                </div>
                                
                                <div class="notify-error">
                                    <?php echo $this->msg; ?>             
                                </div>

                                <input type="text" name="fUsuario" id="fUsuario" class="input-block-level" placeholder="Login"/>
                                <input type="password" name="fSenha" id="fSenha" class="input-block-level" placeholder="Senha"/>

                                <label class="checkbox" for="conectado">
                                <input type="checkbox" name="conectado" id="conectado" />
                               Continuar conectado
                                </label>
                               
                                <input type="submit" class="submit" value="Entrar" />
                                <input type="hidden" name="sOP" value="Logar" />                               
                                <a href="" class="acessoconta">Não consegue acessar a sua conta?</a>
                                <a href="#myModal" role="button" class="btn btn-success cadastre" data-toggle="modal">Cadastre-se</a>
                            </form>

                        </div>
<!-- cadastre -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Cadastre-se</h3>
  </div>
  <div class="modal-body">

   <!-- corpo mordal -->

    <div class="row-fluid">
        <div class="span12">

            <div class="widget-box">

                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Cadastrar Usuário</h5>
                </div>


                <div class="widget-content nopadding formcad">
                    <form class="form-horizontal" method="post" action="/usuario/cadastrar" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fNmUsuario" class="required">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">E-mail <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fEmail"class="required">

                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Grupo Usuário <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdGrupoUsuario" style="width: 200px;">
                                    <?php
                                    foreach ($this->vGrupoUsuario as $grupoUsuario) {
                                    ?>
                                    <option value="<?=$grupoUsuario["id"]?>"><?=$grupoUsuario["nm_grupo_usuario"]?></option>
                                    <?php 
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>


    <div class="control-group">
                            <label class="control-label">Instituição <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdInstituicao" style="width: 200px;">
                                    <?php
                                    foreach ($this->vInstituicao as $instituicao) {

                                    ?>
                                    <option value="<?=$instituicao["id"]?>"><?=$instituicao["razao_social"]?></option>
                                    <?php 
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>



                        <div class="control-group">
                            <label class="control-label">Login <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" id="fLogin" name="fLogin" class="required">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Senha <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="password" id="fSenha" name="fSenha" class="required">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Confirmar Senha <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="password" name="fSenhaConf" id="fSenhaConf" class="required">
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

   <!-- fim corpo mordal -->


  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
  </div>
</div>





                        <!-- cadastre fim -->
                </div> <!--/.span8 -->
            </div>
        </div> <!-- header -->

    </div> <!-- head -->



    <section class="tcontent">
       <div class="row-fluid">

        <div class="presentation">
            <div class="span9">
                <div class="text">
		    <a id="oque"></a>
                    <h2>O que é SINBio?</h2>
                    <p> O SINBIO (Sistema de Iventários Biológicos da Amazônia) é o sistema responsável pelo gerenciamento dos Inventários Biológicos. A Partir dele são extraídas as informações necessárias para o preenchimento dos relatórios de atividades do SISBio na Web.</p>
                    <a href="">Leia mais...</a>
                 </div>
            </div>
            <div class="hidden-phone">
                 <div class="span3">
                        <img src='/images/mobile.png' class="imagemobile" width="299px" height="321px">
                 </div>
            </div>
        </div>
        </div>
        
            <div class="how">
		<a id="comofunciona"></a>
                <h2>Como funciona?</h2>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step1.png'>
                        <p>Pesquisador responsável, forma um grupo de pesquisadores para compor uma expedição.</p>
                    </div>
                </div>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step2.png'>
                        <p>Expedição formada e, devidamente licenciada pelo ICMBio/MMA, parte para campo.</p>
                    </div>
                </div>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step3.png'>
                        <p>Pesquisador coleta amostras durante a expedição</p>
                    </div>
                </div>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step4.png'>
                        <p>Pesquisador determina as características das amostras coletadas.</p>
                    </div>
                </div>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step5.png'>
                        <p>Lider de expedição, cadastra e gerencia as informações de todo esse processo no SINBIO.</p>
                    </div>
                </div>
                <div class="span2">
                    <div class="step">
                        <img src='/images/step6.png'>
                        <p>Os dados padronizados pelo SINBIO são enviados para o SISBIO.</p>
                    </div>
                </div>
        </div>
    </section>





    <footer class="footer">

        
        <div class="foot">
            <div class="row-fluid">
                <div class="span5 offset1">
                    <form class="form-signin">
			<a id="contact"></a>
                        <h2>Contato</h2>
                        <input type="text" name="email" id="" class="input-block-level"></input>
                        <textarea name="" class="input-block-level"></textarea>
                        <input type="submit" name="" id="" class="submit" value="Enviar"></input>
                    </form>
                </div>
                <div class="span6">
                    <div class="infos">
                        <p>Museu Paraense Emílio Goeldi</p>
                        <p>Programa de Pesquisa em Biodiverisade</p>
                        <p>Fone: +55 91 3075-6137</p>
                        <p>Endereço: Av. Perimetral 1197</p>
                        <p>CEP: 66087-423</p>
                    </div>
                </div>  
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="copyright">
                <p>Copyright 2013 - Museu Paraense Emílio Goeldi | Todos os Direitos Reservados.</p>
            </div>
        </div>

    </footer>




<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.7.2.min.js"><\/script>')</script>
<!-- Bootstrap jQuery plugins compiled and minified -->
<script>
  $(document).ready(function(){
    $('.carousel').carousel({
      interval: 4000
    });
  });
</script>
<script src="/js/bootstrap.min.js"></script>

</body>
</html>
