
<h2>Taxonomia Cadastradas</h2>    
<div class="container-fluid">
    <div class="row-fluid">
        <?php
//            foreach ($this->nivelTaxonomico as $nivel):
//                echo $nivel->nm_nivel_taxonomico."<br>";
//                foreach ($this->taxon as $taxon):
//                    
//                    echo "  ";
//                endforeach;
//            endforeach;
        ?>
        <div id="jstree_test">
            <ul>
                <li>Reino
                    <ul style="padding-left: 100px;">
                      <li id="child_node_1">Animalia
                        <ul>
                            <li id="child_node_1_1">Filo
                                <ul>
                                    <li id="child_node_1_2">Annelida</li>
                                    <li>Chordata</li>
                                    <li>Mesozoa</li>
                                    <li>Arthropoda
                                        <ul>
                                            <li id="child_node_1_2_1">Classe
                                                <ul>
                                                    <li id="child_node_1_2_1_1">Insecta
                                                        <ul>
                                                            <li id="child_node_1_2_1_1_1">Ordem
                                                                <ul>
                                                                    <li id="child_node_1_2_1_1_1_1">Diptera
                                                                        <ul>
                                                                            <li id="child_node_1_2_1_1_1_1_1">Família
                                                                                <ul>
                                                                                    <li id="child_node_1_2_1_1_1_1_1_1">Drosophilidae
                                                                                        <ul>
                                                                                            <li id="child_node_1_2_1_1_1_1_1_1_1">Gênero
                                                                                                <ul>
                                                                                                    <li id="child_node_1_2_1_1_1_1_1_1_1_1">Drosophila
                                                                                                        <ul>
                                                                                                            <li id="child_node_1_2_1_1_1_1_1_1_1_1_1">Espécie
                                                                                                                <ul>
                                                                                                                    <li id="child_node_1_2_1_1_1_1_1_1_1_1_1_1">Drosophila paulistorum
                                                                                                                    </li>
                                                                                                                    <li>Drosophila equinoxialis
                                                                                                                    </li>
                                                                                                                    <li>Drosophila septentriosaltans
                                                                                                                    </li>
                                                                                                                </ul>
                                                                                                            </li>
                                                                                                        </ul>
                                                                                                    </li>
                                                                                                </ul>
                                                                                            </li>
                                                                                        </ul>
                                                                                    </li>
                                                                                </ul>
                                                                            </li>
                                                                        </ul>
                                                                    </li>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                          </ul>
                      </li>
                      <li>Fungi</li>
                      <li>Plantae
                      </li>
                      <li>Protista</li>
                      <li>Monera</li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>