<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Atrativo</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/atrativo/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
					
                        <div class="control-group">
							<label class="control-label">Nome do Atrativo: </label>
							<div class="controls">
                                <input type="text" name="fNmAtrativo" value="<?=$this->sNmAtrativo?>" style="width: 400px">
							</div>
						</div>
                                            
						 <div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
