<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Atribuir Variavel para Metodo</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/metodos-variaveis/cadastrar" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Metodo <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name=fMetodo value="<?= $this->fMetodo; ?>" class="required">
                                <input type="hidden" name="fIdMetodo" value="<?= $this->fIdMetodo; ?>" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Metodos Variaveis <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select id="fVariaveis" name="fVariaveis[]" multiple="multiple">

                                    <?php
                                    foreach ($this->vVariavel as $varivel) {
                                        if (array_search($varivel["id"], $this->vMetodosVariaveis)) {
                                            ?>
                                            <option value="<?= $varivel["id"]; ?>" selected="selected"><?= $varivel["nm_variavel"] ?></option>
                                            <?php
                                        } else {
                                            ?>
                                            <option value="<?= $varivel["id"]; ?>"><?= $varivel["nm_variavel"] ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>

                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
