<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Núcleo</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/nucleo/alterar/nId/<?=$this->nId;?>" name="" id="insere-altera" novalidate="novalidate">
						<div class="control-group">
							<label class="control-label">Nome do Núcleo <i class="icon-asterisk"></i>:</label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="fNucleo" class="required"  value="<?=$this->sNmNucleo;?>" style="width: 400px">
							</div>
						</div>
                                            
                                               <div class="control-group">
							<label class="control-label">Descrição <i class="icon-asterisk"></i>:</label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="sDescricao" class="required" value="<?=$this->sDescricao;?>" style="width: 400px">
							</div>
						</div>
                                            
                                                  <div class="control-group">
							<label class="control-label">Representante <i class="icon-asterisk"></i>:</label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="sRepresentante" class="required" value="<?=$this->sRepresentante;?>" style="width: 400px">
							</div>
						</div>
                                            
                                               <div class="control-group">
							<label class="control-label">Orgão Vinculado <i class="icon-asterisk"></i>:</label>
							<div class="controls">
                                                            <input tabindex="1" type="text" name="sOrg_Vinculado" class="required" value="<?=$this->sOrgVinculado;?>" style="width: 400px">
							</div>
						</div>
		
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="submit" value="Alterar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
