<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Alterar Instituição</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/instituicao/alterar/nId/<?=$this->nId;?>" name="" id="insere-altera" novalidate="novalidate">
                        <div class="control-group">
                            <label class="control-label">Razão Social <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fRazaoSocial" value="<?=$this->sRazaoSocial;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Sigla <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fSigla" value="<?=$this->sSigla;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Cnpj <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCnpj" value="<?=$this->sCnpj;?>" class="required">
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Url <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fUrl" value="<?=$this->sUrl;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Nome Dirigente Maior <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fNmDiretor" value="<?=$this->sNmDiretor;?>" class="required">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Cargo Dirigente Maior <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCargoDiretor" value="<?=$this->sCargo_Diretor;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">CPF Dirigente Maior<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCpfDiretor" id="fCpfDiretor" value="<?=$this->sCpfDiretor;?>" class="required">
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Email <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fEmail" value="<?=$this->sEmail;?>" class="required">
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Portaria de Designa&ccedil;&atilde;o:</label>
                            <div class="controls">
                                <input type="text" name="fPDesignacao" value="<?=$this->sPDesignacao;?>" >
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Conv&ecirc;nio:</label>
                            <div class="controls">
                                <input type="text" name="fConvenio" value="<?=$this->sConvenio;?>">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Inicio do Conv&ecirc;nio: </label>
                            <div class="controls">
                                <?php
                                if ($this->sIniConvenio == "") {
                                    $dtiniconv = date('d-m-Y');
                                } else {
                                    $dtiniconv = UtilsDate::formataDataToShow($this->sIniConvenio);
                                }
                                ?>
                                <input type="text" name="fIniConvenio" data-date-format="dd/mm/yyyy"  value="<?php echo $dtiniconv ?>" class="datepicker" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Fim do Conv&ecirc;nio: </label>
                            <div class="controls">
                                <?php
                                if (empty($this->sFimConvenio)) {
                                    ?>
                                    <input type="text" name="fFimConvenio" data-date-format="dd/mm/yyyy" class="datepicker" />
                                    <?php
                                } else {
                                    ?>
                                    <input type="text" name="fFimConvenio" data-date-format="dd/mm/yyyy" value="<?php echo UtilsDate::formataDataToShow($this->sFimConvenio) ?>" class="datepicker" />
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Núcleo <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select tabindex="3" name="fIdNucleo" class="required" style="width: 200px;">
                                    <?php
                                    foreach ($this->vNucleo as $nucleo) {
                                        if ($nucleo["id"] == $this->nIdNucleo)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$nucleo["id"]?>" <?=$sSel?>><?=$nucleo["nm_nucleo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Município <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <select tabindex="3" name="fIdMunicipio" class="required" style="width: 200px;">
                                    <?php
                                    foreach ($this->vMunicipio as $municipio) {
                                        if ($municipio["id"] == $this->nIdMunicipio)
                                            $sSel = 'selected="selected"';
                                        else
                                            $sSel = "";
                                        ?>
                                        <option value="<?=$municipio["id"]?>" <?=$sSel?>><?=$municipio["nm_municipio"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Logradouro<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fLogradouro" value="<?=$this->sLogradouro;?>" class="required">
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Número<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fNumero" value="<?=$this->sNumero;?>" class="required">
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Complemento:</label>
                            <div class="controls">
                                <input type="text" name="fComplemento" value="<?=$this->sComplemento;?>" >
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Bairro<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fBairro" value="<?=$this->sBairro;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Cep<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCep" value="<?=$this->sCep;?>" class="required">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Telefone<i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fTelefone" value="<?=$this->sTelefone;?>" class="required">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Descrição:</label>
                            <div class="controls">
                                <input type="text" name="fDescricao" value="<?=$this->sDescricao;?>" >
                            </div>
                        </div>


                        

                        

                        

                        


                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="alterar" />
                            <input type="submit" value="Alterar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
