<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-info-sign"></i></span>
                    <h5>Cadastrar Institui&ccedil;&atilde;o</h5>
                </div>
                <div class="widget-content nopadding">
                    <form class="form-horizontal" method="post" action="/instituicao/cadastrar" name="" id="insere-altera" novalidate="novalidate">

                        <div class="control-group">
                            <label class="control-label">Razão Social <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input tabindex="1" type="text" name="fRazaoSocial" class="required">
                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Sigla <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fSigla" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Cnpj <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCnpj" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Url <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fUrl" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Nome Dirigente Maior <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fNmDiretor" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Cargo Dirigente Maior <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCargoDiretor" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">CPF Dirigente Maior <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCpfDiretor" id="fCpfDiretor" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Email <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fEmail" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Portaria de Designa&ccedil;&atilde;o:</label>
                            <div class="controls">
                                <input type="text" name="fPDesignacao" >
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Conv&ecirc;nio:</label>
                            <div class="controls">
                                <input type="text" name="fConvenio">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Inicio do Conv&ecirc;nio: </label>
                            <div class="controls">
                                <input type="text" name="fIniConvenio" data-date-format="dd/mm/yyyy" class="datepicker" readonly="true" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Fim do Conv&ecirc;nio: </label>
                            <div class="controls">
                                <input type="text" name="fFimConvenio" data-date-format="dd/mm/yyyy" class="datepicker" readonly="true" />
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Núcleo <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdNucleo" style="width: 200px;">
                                    <?php
                                    foreach ($this->vNucleo as $nucleo) {
                                        ?>
                                        <option value="<?=$nucleo["id"]?>"><?=$nucleo["nm_nucleo"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label">Estado <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdUf" style="width: 200px;">
                                    <?php
                                    foreach ($this->vUf as $uf) {
                                        ?>
                                        <option value="<?=$uf["id"]?>"><?=$uf["nm_uf"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Município <i class="icon-asterisk"></i>:</label>
                            <div class="controls ">
                                <select name="fIdMunicipio" style="width: 200px;">
                                    <?php
                                    foreach ($this->vMunicipio as $municipio) {
                                        ?>
                                        <option value="<?=$municipio["id"]?>"><?=$municipio["nm_municipio"]?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Logradouro <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fLogradouro" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Numero <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fNumero" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Complemento :</label>
                            <div class="controls">
                                <input type="text" name="fComplemento" >

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Bairro <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fBairro" class="required">

                            </div>
                        </div>


                        <div class="control-group">
                            <label class="control-label">CEP <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fCep" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Telefone <i class="icon-asterisk"></i>:</label>
                            <div class="controls">
                                <input type="text" name="fTelefone" class="required">

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Descrição :</label>
                            <div class="controls">
                                <input type="text" name="fDescricao" >

                            </div>
                        </div>

                        <div class="form-actions">
                            <input type="hidden" name="sOP" value="cadastrar" />
                            <input type="submit" value="Salvar" class="btn btn-success">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
                <div class="widget-content nopadding">
                    <ul class="activity-list">
                        <li><a href="#">
                                <i class="icon-asterisk"></i>
                                <span>Campo obrigatório</span>
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
