<?= $this->doctype() ?>
<html lang="en">

    <head>
        <title>Painel de Controle</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/css/sinbio/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/sinbio/bootstrap-responsive.min.css" />
        <link rel="stylesheet" href="/css/sinbio/style.css" />
        <link rel="stylesheet" href="/css/sinbio/media.css" class="skin-color" />
        <link rel="stylesheet" href="/css/sinbio/colorpicker.css" />
        <link rel="stylesheet" href="/css/sinbio/datepicker.css" />
        <link rel="stylesheet" href="/css/sinbio/uniform.css" />
        <link rel="stylesheet" href="/css/sinbio/select2.css" />
        <link rel="stylesheet" href="/plugin/jquery.alerts/jquery.alerts.css" />
        <link rel="stylesheet" href="/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="/css/buttons.dataTables.min.css" />
        <?= $this->layout()->includeCss ?>

        <script src="js/less-1.4.1.min.js" type="text/javascript"></script>
        <script src="http://code.jquery.com/jquery.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="/js/modernizr.js"></script>
        <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
        <![endif]-->
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->



    </head>

    <body>

        <div class="selos">
            <a href="" class="brasil">brasil</a>
            <a href="" class="acesso">acesso à informação</a>

        </div>


        <!--top-Header-menu-->
        <?php
//á
        $nHora = (int) date("H");

        switch (true) {
            case $nHora >= 6 && $nHora < 12:
                $sSaudacao = "Bom dia ";
                break;
            case $nHora >= 12 && $nHora < 18:
                $sSaudacao = "Boa tarde ";
                break;
            case ($nHora >= 18 && $nHora <= 23) || ($nHora >= 0 && $nHora < 6):
                $sSaudacao = "Boa noite ";
                break;
        }




        $auth = Zend_Auth::getInstance();
        $vUsuarioLogado = $auth->getIdentity();
        ?>

        <div class="head-inner">
            <div class="row-fluid">

                <div class="bartop">
                    <div class="span3">
                        <div class="sinbio">
                            <a href="">sinbio</a>
                        </div>
                    </div>

                    <div class="span5 offset3">
                        <div class="conta">
                            <p class="usuario"><?= $sSaudacao . " " . $vUsuarioLogado['nm_usuario'] ?> !</p>
                        </div>
                    </div>

                    <div class="span1">
                        <div class="bt-user">
                            <div class="btn-group">
                                <button class="btn btn-success"><i class="icon-user icon-white"></i><?= $vUsuarioLogado['login']; ?></button>
                                <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>           <a title="" href="/alterar-senha/alterar/nId/<?php echo $vUsuarioLogado['id']; ?>">

                                            <img src="/img/icons/ico-key.png"/>
                                            <span class="text">Configuração</span>
                                        </a>
                                    </li>
                                    <li>  <a title="" href="/login/logoff">
                                            <i class="icon-off"></i>
                                            <span class="text">Logout</span>
                                        </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <!-- CONTENT -->
        <section class="tcontent">

            <div class="area row-fluid">
                <div class="span5">
                    <h1>Sistema de Inventário</h1>
                </div>

            </div>

            <div class="content-inner row-fluid">


                <div class="span4">

                    <div class="navside">

                        <div class="amostras_cadastradas">

                            <div class="row-fluid">
                                <?php
                                $bd = Zend_Db_Table::getDefaultAdapter();

                                //RECUPERA TOTAL DE AMOSTRAS CADASTRADAS NO SISTEMA
                                $amostraSql = $bd->query("
												SELECT *
												FROM	coleta_amostra
											");
                                $rs = $amostraSql->fetchAll();
                                $total = count($rs);
                                ?>
                                <span class="numero_amostra"><?php echo $total; ?></span>
                                <h3>Amostras cadastradas</h3>
                            </div>

                        </div>
                        <?php
                        if ($this->vMenu == "") {
                            
                        } else {
                            foreach ($this->vMenu as $vModulo) {
                                
                                $labelMenu;
                                if ($vModulo["modulo"] == "Segurança") {
                                    $labelMenu = "Cadastro de Usuários";
                                } else {
                                    $labelMenu = $vModulo['modulo'];
                                }
                                
                                //Retira menu projetos/programas, medida temporária.
                                if ($vModulo["modulo"] == "Projetos/Programas"){
                                    continue;
                                }
                                
                                //Highlight do menu selecionado, medida temporária.
                                if ( !strcasecmp( substr($labelMenu, 0, 3), substr($this->layout()->nmController, 0, 3) ) ){
                                    ?> <a style="    background-color: rgba(150, 199, 210, 0.55)" href="/<?= $vModulo["programas"][0]["controller"] . "/index" ?>">  <img src='/<?= $vModulo["ico"] ?>' /> <p> <?= $labelMenu ?> </p></a><?php
                                }else if ($this->layout()->nmController == "usuario" && $labelMenu =="Cadastro de Usuários"){
                                    ?> <a style="    background-color: rgba(150, 199, 210, 0.55)" href="/<?= $vModulo["programas"][0]["controller"] . "/index" ?>">  <img src='/<?= $vModulo["ico"] ?>' /> <p> <?= $labelMenu ?> </p></a><?php
                                }else if ($this->layout()->nmController == "uf" && $labelMenu =="Localidade"){
                                    ?> <a style="    background-color: rgba(150, 199, 210, 0.55)" href="/<?= $vModulo["programas"][0]["controller"] . "/index" ?>">  <img src='/<?= $vModulo["ico"] ?>' /> <p> <?= $labelMenu ?> </p></a><?php
                                }else{
                                    ?> <a href="/<?= $vModulo["programas"][0]["controller"] . "/index" ?>">  <img src='/<?= $vModulo["ico"] ?>' /> <p> <?= $labelMenu ?> </p></a><?php
                                }
                            }
                        }
                        ?>

                    </div>


                </div>

                <div class="span8 row-fluid">
                    <div id="breadcrumb">
                        <a href="/sinbio/internas/pagina-inicial" title="Página Inicial" class="tip-bottom"><i class="icon-home"></i> Página Inicial</a>
                        <?php
                        //****PAULO ROSA******
                        /*
                          Alteração dos label's no menu, Requesito presente no backlog (07/06/2016)
                         */
                        $labelBreadCumb;
                        if ($this->layout()->nmPrograma == "pessoas") {
                            $labelBreadCumb = "Pesquisas";
                        } else if ($this->layout()->nmPrograma == "segurança") {
                            $labelBreadCumb = "Cadastro de Usuários";
                        } else {
                            $labelBreadCumb = $this->layout()->nmPrograma;
                        }
                        ?>
                        <a href="/sinbio/<?= $this->layout()->nmController; ?>/index" class="current tip-bottom" title="<?= $this->layout()->nmPrograma; ?>"><?= $labelBreadCumb; ?></a>
                        <a href="#"><?= $this->layout()->nmOperacao; ?></a>
                    </div>
                    <?= ($this->layout()->msg) ? $this->layout()->msg : ""; ?>
                    <?= $this->layout()->content; ?>

                </div>
            </div>
        </section>

        <!-- FIM CONTENT -->


        <!-- -->
        <footer class="footer">
            <div class="copyright2">
                <p>Copyright 2013 - Museu Paraense Emílio Goeldi | Todos os Direitos Reservados.</p>
                <div class="sti">
                    <img src='/images/sti.png'/>
                </div>
            </div>


        </footer>




        <!-- -->











    </body>
    <script src="/js/jquery-1.12.0.min.js"></script>
    <script src="/js/geral/jquery.min.js"></script>
    <script src="/js/jquery.maskedinput.min.js"></script>
    <script src="/js/geral/jquery.ui.custom.js"></script>
    <script src="/js/geral/bootstrap.min.js"></script>
    <script src="/js/geral/bootstrap-colorpicker.js"></script>
    <script src="/js/geral/bootstrap-datepicker.js"></script>
    <script src="/js/geral/bootstrap-datepicker.pt-BR.js"></script>    
    <script src="/js/geral/jquery.uniform.js"></script>
    <script src="/js/geral/select2.min.js"></script>
    <script src="/js/geral/maruti.js"></script>
    <script src="/js/geral/maruti.form_common.js"></script>
    <script src="/plugin/jquery.alerts/jquery.alerts.js"></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <?= $this->layout()->includeJs ?>

    <?php
//  echo '<pre>';
//  print_r($this->vMenu);
    ?>
</html>
