<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Cadastrar Município</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal" method="post" action="/municipio/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
				<div class="control-group">
							<label class="control-label">Nome <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fNmMunicipio"  value="<?=$this->sNome;?>" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">DDD <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fddd" value="<?=$this->sDDD;?>" class="required">

							</div>
                                                </div>

                                                <div class="control-group">
                                                    <label class="control-label">Capital <i class="icon-asterisk"></i>:</label>
                                                    <div class="controls">
                                                        
                                                        <?php
                                                        
                                                        if ($this->sCapital == "1") {
                                                            $checked = 'checked="checked" ';
                                                        }else{
                                                             $checked = "";
                                                        }
                                                        ?>
                                                        <input type="checkbox" name="fCapital" value="1" <?php echo $checked; ?>> 
                                                    </div>
                                                </div>
						<div class="control-group">
							<label class="control-label">UF <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select tabindex="3" name="fIdUf" class="required" style="width: 200px;">
									<?php
									foreach ($this->vUf as $uf) {
										if ($uf["id"] == $this->nIdUf)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$uf["id"]?>" <?=$sSel?>><?=$uf["nm_uf"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
						
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
