<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Alterar Taxon</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/taxon/alterar/nId/<?=$this->nId?>" name="" id="insere-altera" novalidate="novalidate">
				
                                            	<div class="control-group">
							<label class="control-label">Autor,Ano :</label>
							<div class="controls">
								<input type="text" name="fAutorAno" value="<?=$this->sAutorAno;?>" >
							</div>
						</div>
                                            
                                                <div class="control-group">
							<label class="control-label">Nivel Taxonomico  <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<select name="fIdNivelTaxonomico" class="required" style="width: 200px;">
									<?php
									foreach ($this->vNivel as $nivel) {
										if ($nivel["id"] == $this->nIdNivel)
											$sSel = 'selected="selected"';
										else
											$sSel = "";
									?>
									<option value="<?=$nivel["id"]?>" <?=$sSel?>><?=$nivel["nivel_taxonomico"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                            
                                            
                                                <div class="control-group">
							<label class="control-label">Nome do Taxon <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fTaxon" value="<?=$this->sTaxon;?>" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Taxon de Refer&ecirc;ncia  <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fTaxonSuperior" value="<?=$this->sTaxonSuperior;?>" class="required">

							</div>
                                                </div>

                                                  <div class="control-group">
                                                <label class="control-label">Data: </label>
                                                <div class="controls">
                                                    <input type="text" name="fData" data-date-format="dd-mm-yyyy" value="<?php echo UtilsDate::formataDataToShow($this->sData) ?>" class="datepicker" />
                                                </div>
                                            </div>

                                               <div class="control-group">
                                                   <label class="control-label">Refer&ecirc;ncia Bibliogr&aacute;fica <i class="icon-asterisk"></i>:</label>
                                                    <div class="controls">
                                                        <input type="text" name="fReferencia" value="<?=$this->sReferencia;?>" class="required"> 
                                                    </div>
                                                </div>
                                            
                                               <div class="control-group">
                                                    <label class="control-label">Observacao <i class="icon-asterisk"></i>:</label>
                                                    <div class="controls">
                                                        <input type="text" name="fObservacao" value="<?=$this->sObservacao;?>" class="required" > 
                                                    </div>
                                                </div>
						
						
						<div class="form-actions">
							<input type="hidden" name="sOP" value="alterar" />
							<input type="hidden" name="nId" value="<?=$this->nId?>" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
