<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Cadastrar Taxon</h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/taxon/cadastrar" name="" id="insere-altera" novalidate="novalidate">
						
                                            	<div class="control-group">
							<label class="control-label">Autor,Ano :</label>
							<div class="controls">
								<input type="text" name="fAutorAno">
							</div>
						</div>
                                           
                                             	<div class="control-group">
							<label class="control-label">Nivel Taxonomico <i class="icon-asterisk"></i>:</label>
							<div class="controls ">
								<select name="fIdNivelTaxonomico" style="width: 300px;">
									<?php
									foreach ($this->vNivel as $nivel) {
									?>
									<option value="<?=$nivel["id"]?>"><?=$nivel["nivel_taxonomico"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                            
                                            
                                            
                                            <div class="control-group">
							<label class="control-label">Nome do Taxon <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fTaxon" class="required">
							</div>
						</div>
						<div class="control-group">
                                                    <label class="control-label">Taxon de Refer&ecirc;ncia <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fTaxonSuperior" class="required">

							</div>
                                                </div>

                                                  <div class="control-group">
                                                <label class="control-label">Data: </label>
                                                <div class="controls">
                                                    <input type="text" name="fData" data-date-format="dd-mm-yyyy" value="<?php echo date("d-m-Y") ?>" class="datepicker" />
                                                </div>
                                            </div>

                                               <div class="control-group">
                                                    <label class="control-label">Refer&ecirc;ncia Bibliogr&aacute;fica <i class="icon-asterisk"></i>:</label>
                                                    <div class="controls">
                                                        <input type="text" name="fReferencia" class="required"> 
                                                    </div>
                                                </div>
                                            
                                               <div class="control-group">
                                                    <label class="control-label">Observacao <i class="icon-asterisk"></i>:</label>
                                                    <div class="controls">
                                                        <input type="text" name="fObservacao" class="required"> 
                                                    </div>
                                                </div>
						
						
						
						<div class="form-actions">
							<input type="hidden" name="sOP" value="cadastrar" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#"><i class="icon-asterisk"></i><span>Campo obrigatório</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
