
<h2>Coleções Cadastradas</h2>    
<?php
if ($this->vMenu == "") {
    
} else {
    foreach ($this->vMenu as $vModulo) {
        if ($vModulo["modulo"] == "Coleção") {
            ?>
            <ul class="nav nav-tabs">
                <?php
                foreach ($vModulo["programas"] as $vPrograma) {


                    if ($vPrograma['controller'] == "colecao") {
                        ?>
                        <li class="active">  
                        <?php } else {
                            ?>
                        <li> 
                            <?php
                        }
                        ?>
                        <a href="/<?= $vPrograma["controller"] . "/index" ?>"><?= $vPrograma["programa"] ?></a></li>
                    <?php
                }
                ?>
            </ul>
            <?php
        }
    }
}
?>


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="bs-example">
                <table class="tabela display" >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nome da Coleção</th>
                            <th>Sigla</th>
                            <th>Curador</th>
                            <th>Email Curador</th>
                            <th>Telefone Curador</th>
                        </tr>
                    </thead>

                    <tbody>

                        <?php foreach ($this->paginator as $value) {
                            ?>
                            <tr>
                                <td><?php echo $value["id"]; ?></td>
                                <td><?php echo $value["nm_colecoes"]; ?></td>
                                <td><?php echo $value["sigla"]; ?></td>
                                <td><?php echo $value["nm_usuario"]; ?></td>
                                <td><?php echo $value["email"]; ?></td>
                                <td><?php echo $value["telefone"]; ?></td>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>