<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title">
					<span class="icon"><i class="icon-info-sign"></i></span>
					<h5>Cadastrar Projetos/Programas </h5>
				</div>
				<div class="widget-content nopadding">
					<form class="form-horizontal form-scroll" method="post" action="/projeto-programa/cadastrar" name="" id="insere-altera" novalidate="novalidate">
						<div class="control-group">
							<label class="control-label">Sigla <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input tabindex="1" type="text" name="fSigla" class="required">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Nome Do Projeto/Programa <i class="icon-asterisk"></i>:</label>
							<div class="controls">
								<input type="text" name="fProjetoPrograma" class="required">

							</div>
						</div>
                                            
                                                <div class="control-group">
							<label class="control-label">Descrição :</label>
							<div class="controls">
								<input type="text" name="fDescricao">

							</div>
						</div>
                                                <div class="control-group">
                                                <label class="control-label">Data Inicio: </label>
                                                <div class="controls">
                                                    <input type="text" name="fDataInicio" data-date-format="dd-mm-yyyy" value="<?php echo date("d-m-Y") ?>" class="datepicker" />
                                                </div>
                                            </div>
                                            
                                              <div class="control-group">
                                                <label class="control-label">Data Fim: </label>
                                                <div class="controls">
                                                    <input type="text" name="fDataFim" data-date-format="dd-mm-yyyy" value="<?php echo date("d-m-Y") ?>" class="datepicker" />
                                                </div>
                                            </div>
                                            
                                               	<div class="control-group">
							<label class="control-label">Cordenador <i class="icon-asterisk"></i>:</label>
							<div class="controls ">
								<select name="fIdCurador" style="width: 200px;">
									<?php
									foreach ($this->vCurador as $Curador) {
									?>
									<option value="<?=$Curador["id"]?>"><?=$Curador["nm_usuario"]?></option>
									<?php 
									}
									?>
								</select>
							</div>
						</div>
                                            
                                            	
                                            
						<div class="form-actions">
							<input type="hidden" name="sOP" value="cadastrar" />
							<input type="submit" value="Salvar" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget-box widget-no-margin">
				<div class="widget-title"><span class="icon"><i class="icon-comment"></i></span><h5>Legenda</h5></div>
				<div class="widget-content nopadding">
					<ul class="activity-list">
						<li><a href="#">
							<i class="icon-asterisk"></i>
							<span>Campo obrigatório</span>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
